#ifndef __VARIABLES__H__
#define __VARIABLES__H__

#define ARENA_HEIGHT 40
#define ARENA_WIDTH 80
#define POINT_DE_VIE_MAX 100
#define VITESSE_MAX_ROBOT 100
#define VITESSE_MAX_MISSILE 100
#define MISSILE_MAX 2
#define TAILLE_MEMOIRE 100
#define ROBOTS_CHARACTERISTICS_HEIGHT 9
#define ROBOTS_CHARACTERISTICS_WIDTH 80

#endif
